Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/9_Credit_card_fraud.csv')

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5969,6634,-1.611463,0.190648,0.901715,1.531254,-1.535865,0.799245,1.513786,0.495829,0.200390,...,0.211223,0.007477,1.026272,0.057628,-0.024955,-0.368263,0.081684,0.140669,458.92,0.0
5970,6635,-1.420272,1.449354,1.320110,-1.894320,0.913695,0.454601,0.894179,-0.385450,2.433841,...,-0.529027,-0.368394,-0.247773,-1.189156,-0.126040,0.701487,0.277333,-0.222694,0.77,0.0
5971,6637,-1.206696,0.284728,2.152053,-2.850437,-0.437285,-0.238376,-0.333341,0.334679,2.870542,...,0.039460,0.464476,-0.457193,-0.556105,0.517579,0.008006,0.366054,0.185008,14.00,0.0
5972,6644,1.067611,0.091006,-0.153917,0.704233,0.113894,-0.826866,0.567690,-0.464181,0.957295,...,-0.476723,-1.410090,-0.037550,-0.177773,0.321810,0.114930,-0.109640,0.023205,139.90,0.0
5973,6645,-0.535272,-0.132299,2.180041,1.018303,-1.498819,0.529570,0.420147,0.045445,1.543919,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5974 entries, 0 to 5973
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    5974 non-null   int64
 1   V1      5974 non-null   float64
 2   V2      5974 non-null   float64
 3   V3      5974 non-null   float64
 4   V4      5974 non-null   float64
 5   V5      5974 non-null   float64
 6   V6      5974 non-null   float64
 7   V7      5974 non-null   float64
 8   V8      5974 non-null   float64
 9   V9      5974 non-null   float64
 10  V10     5974 non-null   float64
 11  V11     5974 non-null   float64
 12  V12     5974 non-null   float64
 13  V13     5974 non-null   float64
 14  V14     5974 non-null   float64
 15  V15     5974 non-null   float64
 16  V16     5974 non-null   float64
 17  V17     5974 non-null   float64
 18  V18     5973 non-null   float64
 19  V19     5973 non-null   float64
 20  V20     5973 non-null   float64
 21  V21     5973 non-null   float64
 22  V22     5973 non-null   float64
 23  V23     5973 non-null   float64
 24  V24     5973 non-null   float64
 25  V25     5973 non-null   float64
 26  V26     5973 non-null   float64
 27  V27     5973 non-null   float64
 28  V28     5973 non-null   float64
 29  Amount  5973 non-null   float64
 30  Class   5973 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.4 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    5970
1.0       3
Name: Class, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(5970, 31)
(3, 31)

In [10]:
# statistical measures of the data
legit.Amount.describe()

count    5970.000000
mean       64.965707
std       192.429839
min         0.000000
25%         4.450000
50%        15.620000
75%        56.485000
max      7712.430000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count      3.000000
mean     256.310000
std      264.880121
min        0.000000
25%      119.965000
50%      239.930000
75%      384.465000
max      529.000000
Name: Amount, dtype: float64

In [12]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,2677.40201,-0.264965,0.285625,0.844580,0.102656,0.000958,0.195420,0.018542,-0.039195,0.397472,...,0.055426,-0.043268,-0.161540,-0.036683,0.028985,0.089890,-0.040132,0.025238,0.006163,64.965707
1.0,1780.00000,-2.553039,0.184644,-0.293711,2.872264,0.005330,-0.855718,-0.549831,0.308239,-1.093098,...,0.599742,0.294921,-0.177321,0.361160,-0.020311,0.056068,-0.170050,0.015979,-0.086847,256.310000

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [13]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5432,5420,0.981928,0.066696,1.016903,0.987465,0.223847,1.784118,-0.814973,0.620153,1.348653,...,-0.040351,0.277336,0.189165,-1.098377,-0.043907,-0.439072,0.091267,0.005101,0.00,0.0
4603,3958,-0.250191,0.228191,1.261547,-0.868134,0.183148,-0.547637,-0.005619,-0.027883,1.373310,...,-0.136560,-0.102934,0.026774,0.002985,-0.337875,0.056862,0.049723,0.035500,8.79,0.0
1313,1029,-2.582175,2.213807,1.749030,-2.389200,0.713566,-0.214627,1.962399,-1.415934,3.074449,...,-0.757745,0.042332,-0.220885,0.020242,-0.015996,0.556129,0.226622,-0.904042,0.92,0.0
3997,3638,0.347370,-1.160738,1.011706,1.615779,-0.796071,1.240521,-0.421147,0.322980,1.813689,...,0.111878,0.029622,-0.258820,-0.322427,0.096853,-0.444063,0.011192,0.076735,360.46,0.0
2154,1665,-2.323486,2.018356,0.127581,-2.289277,0.416302,0.564754,0.269058,0.491662,1.498929,...,-0.359707,-0.530568,-0.157659,-1.736973,0.164332,0.877502,1.098095,0.625987,0.99,0.0

In [16]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
718,541,-0.623525,0.176955,2.565715,1.544280,0.109686,0.055218,0.259801,-0.192566,-0.320106,...,0.387800,1.408297,0.019451,0.545551,-1.357580,-0.332164,-0.138540,-0.200151,67.10,0.0
959,726,-0.393673,1.030889,1.295537,-0.045917,0.026069,-0.658290,0.599278,0.098848,-0.585184,...,-0.214127,-0.616465,-0.007490,0.264323,-0.203998,0.055965,0.236596,0.087496,9.44,0.0
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1.0
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1.0
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1.0

In [17]:
new_dataset['Class'].value_counts()

0.0    492
1.0      3
Name: Class, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,2706.662602,-0.272248,0.330842,0.953662,0.194608,0.00889,0.241798,0.026501,-0.005843,0.469991,...,0.065836,-0.055762,-0.168813,-0.014145,0.113053,0.059432,-0.042187,0.006762,-0.021214,52.6825
1.0,1780.000000,-2.553039,0.184644,-0.293711,2.872264,0.00533,-0.855718,-0.549831,0.308239,-1.093098,...,0.599742,0.294921,-0.177321,0.361160,-0.020311,0.056068,-0.170050,0.015979,-0.086847,256.3100

Splitting the data into Features & Targets

In [19]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [20]:
print(X)

      Time        V1        V2        V3        V4        V5        V6  \
5432  5420  0.981928  0.066696  1.016903  0.987465  0.223847  1.784118
4603  3958 -0.250191  0.228191  1.261547 -0.868134  0.183148 -0.547637
1313  1029 -2.582175  2.213807  1.749030 -2.389200  0.713566 -0.214627
3997  3638  0.347370 -1.160738  1.011706  1.615779 -0.796071  1.240521
2154  1665 -2.323486  2.018356  0.127581 -2.289277  0.416302  0.564754
...    ...       ...       ...       ...       ...       ...       ...
718    541 -0.623525  0.176955  2.565715  1.544280  0.109686  0.055218
959    726 -0.393673  1.030889  1.295537 -0.045917  0.026069 -0.658290
541    406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
623    472 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823
4920  4462 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788

            V7        V8        V9  ...       V20       V21       V22  \
5432 -0.814973  0.620153  1.348653  ... -0.301938 -0.040351  0.277336
4603 -0.005619 -0.027883  1.373310  ...  0.239537 -0.136560 -0.102934
1313  1.962399 -1.415934  3.074449  ...  2.187643 -0.757745  0.042332
3997 -0.421147  0.322980  1.813689  ...  0.506887  0.111878  0.029622
2154  0.269058  0.491662  1.498929  ...  1.050769 -0.359707 -0.530568
...        ...       ...       ...  ...       ...       ...       ...
718   0.259801 -0.192566 -0.320106  ... -0.074807  0.387800  1.408297
959   0.599278  0.098848 -0.585184  ...  0.107735 -0.214127 -0.616465
541  -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
623   0.325574 -0.067794 -0.270953  ...  2.102339  0.661696  0.435477
4920  0.562320 -0.399147 -0.238253  ... -0.430022 -0.294166 -0.932391

           V23       V24       V25       V26       V27       V28  Amount
5432  0.189165 -1.098377 -0.043907 -0.439072  0.091267  0.005101    0.00
4603  0.026774  0.002985 -0.337875  0.056862  0.049723  0.035500    8.79
1313 -0.220885  0.020242 -0.015996  0.556129  0.226622 -0.904042    0.92
3997 -0.258820 -0.322427  0.096853 -0.444063  0.011192  0.076735  360.46
2154 -0.157659 -1.736973  0.164332  0.877502  1.098095  0.625987    0.99
...        ...       ...       ...       ...       ...       ...     ...
718   0.019451  0.545551 -1.357580 -0.332164 -0.138540 -0.200151   67.10
959  -0.007490  0.264323 -0.203998  0.055965  0.236596  0.087496    9.44
541  -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
623   1.375966 -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00
4920  0.172726 -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93

[495 rows x 30 columns]

In [21]:
print(Y)

5432    0.0
4603    0.0
1313    0.0
3997    0.0
2154    0.0
       ...
718     0.0
959     0.0
541     1.0
623     1.0
4920    1.0
Name: Class, Length: 495, dtype: float64

Split the data into Training data & Testing Data

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(495, 30) (396, 30) (99, 30)

Model Training

Logistic Regression

In [24]:
model = LogisticRegression()

In [25]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [26]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  1.0

In [28]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [29]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.98989898989899